{{- if and .Values.postgresql.tls.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.postgresql.tls.certificatesSecret }}
  namespace: {{ .Release.Namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
type: Opaque
data:
  tls.crt: 
  tls.key: 
  ca.crt: 
{{- end }}